# Generated by Django 4.1.3 on 2023-04-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_options_alter_paragraph_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theme',
            name='level',
            field=models.CharField(choices=[('base', 'Базовый'), ('advanced', 'Продвинутый'), ('expert', 'Экспертный')], default='base', max_length=50),
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ManyToManyField(to='main.course', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
