# Generated by Django 4.1.3 on 2023-04-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_child_theme_level_coursetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('base', 'Базовый'), ('advanced', 'Продвинутый'), ('expert', 'Экспертный')], default='base', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.RenameField(
            model_name='course',
            old_name='child',
            new_name='demo',
        ),
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, choices=[('child', 'Детский'), ('dev', 'Программирование'), ('design', 'Дизайн'), ('office', 'Офисный')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='CourseTag',
        ),
        migrations.AddField(
            model_name='courselevel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='main.course'),
        ),
    ]
