# Generated by Django 4.1.3 on 2023-04-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_courselevel_options_alter_course_demo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='theme',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер темы'),
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Спецификация')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='main.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
            },
        ),
    ]
