# Generated by Django 4.1.3 on 2023-04-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_course_description_theme_order_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, choices=[('child', 'Детский'), ('dev', 'Программирование'), ('design', 'Дизайн'), ('office', 'Офисный')], default='', max_length=50, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='spec',
            name='text',
            field=models.TextField(default='', verbose_name='Спецификация'),
        ),
    ]
