# Generated by Django 4.1.3 on 2023-06-07 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_course_description_alter_course_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', verbose_name='Спецификация')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='main.courselevel', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
            },
        ),
    ]
