# Generated by Django 4.1.3 on 2023-06-08 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_levelspec'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselevel',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='courselevel',
            name='name',
            field=models.CharField(default='Курс', max_length=200, verbose_name='Название уровня'),
        ),
    ]
