# Generated by Django 4.1.3 on 2023-07-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='programm',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pdfs/', verbose_name='Программа курса'),
        ),
    ]
