# Generated by Django 4.1.3 on 2023-07-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_app_course_apps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='apps',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='main.app', verbose_name='Изучаемые приложения'),
        ),
    ]
